version: "3.0"
services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk
  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
networks:
  docker_elk:
    driver: bridge
