version: '3'
services:
  nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - /Users/xx/php/:/var/wwwroot/:rw
        - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./log/nginx/:/var/log/nginx/:rw
      networks:  
        - net-php
  php:
      build: ./php/php71/
      expose:
        - "9000"
      volumes:
        - /Users/xx/php/:/var/wwwroot/:rw
        - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
        - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        - ./log/php-fpm/:/var/log/php-fpm/:rw
      networks:  
        - net-redis
        - net-php
        - net-memcached
  memcached:
      image: memcached:alpine
      ports:
        - "11211:11211"
      networks:  
        - net-memcached
  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      networks:
        - net-redis
networks:       
    net-php:
        driver: bridge
    net-memcached:
        driver: bridge
    net-redis:
        driver: bridge
